build:
    nodes:
        analysis:
            environment:
                php:
                    version: 7.2
            cache:
                disabled: false
                directories:
                    - ~/.composer/cache
            project_setup:
                override: true
    dependencies:
        override:
            - composer install --no-interaction --prefer-dist
            
filter:
    excluded_paths:
        - docs

build_failure_conditions:
    - 'elements.rating(<= B).new.exists'                        # No new classes/methods with a rating of B or worse allowed
    - 'issues.severity(>= MAJOR).new.exists'                    # New issues of major or higher severity
    - 'project.metric_change("scrutinizer.test_coverage", < 0)' # Code Coverage decreased from previous inspection
