build:
    nodes:
        analysis:
            environment:
                php:
                    version: 7.2
            cache:
                disabled: false
                directories:
                    - ~/.composer/cache
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run
    dependencies:
        override:
            - composer install --no-interaction --prefer-dist

tools:
    external_code_coverage:

filter:
    excluded_paths:
        - docs

build_failure_conditions:
    - 'elements.rating(<= B).new.exists'                        # No new classes/methods with a rating of B or worse allowed
    - 'issues.severity(>= MAJOR).new.exists'                    # New issues of major or higher severity
