version: '3.4'

x-php-common-conf:
  - &php-common-conf
    volumes:
      - .:/usr/src/myapp
      - ./cache:/root/composer/cache
    environment:
      - LANG=en_US.UTF-8
      - COMPOSER_CACHE_DIR=/root/composer/cache
    depends_on:
      - languagetools

services:
  php7.2:
    build: docker/php7.2
    <<: *php-common-conf

  php7.3:
    build: docker/php7.3
    <<: *php-common-conf

  php7.4:
    build: docker/php7.4
    <<: *php-common-conf

  jamspell:
    build: docker/jamspell
    ports:
      - 5466:8080

  languagetools:
    image: silviof/docker-languagetool
